apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-no-pv
  labels:
    app: nfs-server-no-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-no-pv
  template:
    metadata:
      labels:
        app: nfs-server-no-pv
    spec:
      containers:
        - name: server
          image: gcr.io/diamond-privreg/hqv85942/nfsuserserver:confluenceexample
          ports:
            - containerPort: 2049
              protocol: UDP
            - containerPort: 20048
              protocol: UDP
            - containerPort: 111
              protocol: UDP
            - containerPort: 69
              protocol: UDP
          command: ["/bin/bash"]
          args: ["-c", "bash startupnopv.sh && sleep infinity"]

          resources:
            limits:
              memory: 50Mib
              cpu: 100m
            requests:
              memory: 20Mib
              cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-no-pv
  labels:
    app: nfs-server-no-pv
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: 111
    - name: nfsd
      port: 2049
      protocol: UDP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: UDP
      targetPort: 20048
    - name: tftp
      port: 69
      protocol: UDP
      targetPort: 69
  sessionAffinity: None
  selector:
    app: nfs-server-no-pv
