apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-tftp
  labels:
    app: nfs-tftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-tftp
  template:
    metadata:
      labels:
        app: nfs-tftp
    spec:
      containers:
        - name: server
          image: ghcr.io/epics-containers/nfsv2-tftp-server:main
          ports:
            - containerPort: 2049
              protocol: UDP
            - containerPort: 20048
              protocol: UDP
            - containerPort: 111
              protocol: UDP
            - containerPort: 69
              protocol: UDP
          command: ["/bin/bash"]
          args: ["-c", "bash /scripts/startup.sh && sleep infinity"]

          resources:
            limits:
              memory: 50Mi
              cpu: 100m
            requests:
              memory: 20Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-tftp
  labels:
    app: nfs-tftp
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: 111
    - name: nfsd
      port: 2049
      protocol: UDP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: UDP
      targetPort: 20048
    - name: tftp
      port: 69
      protocol: UDP
      targetPort: 69
  # a pollux static IP
  loadBalancerIP: "172.23.168.198"
  sessionAffinity: None
  selector:
    app: nfs-tftp
