build-image:
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  script:
    - echo "Building image..."
    - env | grep "CI_"
    - /bin/sh ./kanikobuild.sh
    - echo "Done"
    
