#!/bin/sh
defaultwait=65
service rpcbind stop
bash /etc/init.d/nfs-user-server stop
iplist=`netstat -tn | grep : | awk '{print $5}'`
for ip in $iplist
do
echo /exports/nfs_server ${ip%:*}\(rw,sync,no_root_squash,insecure\) >> /etc/exports
done
sleep ${1:-defaultwait}
rpcbind -w
bash /etc/init.d/nfs-user-server start