#!/bin/bash

### BEGIN INIT INFO
# Provides:		nfs-user-server nfs-server
# Required-Start:	$network rpcbind
# Required-Stop:	$network rpcbind
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Startup script for the NFS servers.
### END INIT INFO

set -e

DESC="NFS servers"

test -x /usr/sbin/rpc.nfsd -a -f /etc/exports || exit 0

case "$1" in
start)
	printf "Starting %s:" "$DESC"
	start-stop-daemon --start --oknodo --quiet --exec /usr/sbin/rpc.nfsd -- -r -P 2049
	printf " nfsd"
	start-stop-daemon --start --oknodo --quiet --exec /usr/sbin/rpc.mountd -- -r -P 20048
	printf " mountd"
	printf ".\n"
	;;
stop)
	printf "Stopping %s:" "$DESC"
	start-stop-daemon --stop --oknodo --quiet --exec /usr/sbin/rpc.mountd
	printf " mountd"
	start-stop-daemon --stop --oknodo --quiet --exec /usr/sbin/rpc.nfsd
	printf " nfsd"
	printf ".\n"
	;;
reload | force-reload)
	printf "Reloading %s' configuration files.\n" "$DESC"
	start-stop-daemon --stop --signal 1 --quiet --exec /usr/sbin/rpc.mountd
	start-stop-daemon --stop --signal 1 --quiet --exec /usr/sbin/rpc.nfsd
	;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
*)
	printf "Usage: %s {start|stop|restart|reload|force-reload}\n" "$0" >&2
	exit 1
	;;
esac

exit 0
