#!/bin/bash
cp /var/log/syslog /syslogcopy 
lastpacket=$(netstat -s | tail -n 25 | grep packets)
    echo `date +"%T.%N"` >> /packetlog
    echo "$newpacket" >> /packetlog
while true
do
newpacket=$(netstat -s | tail -n 25 | grep packets)
if [ "$newpacket" != "$lastpacket" ] 
then
    echo `date +"%T.%N"` >> /packetlog
    echo "$newpacket" >> /packetlog
    echo `diff -u --suppress-common-lines /var/log/syslog /syslogcopy` >> /packetlog
    echo `diff -u --suppress-common-lines /var/log/syslog /syslogcopy`
    lastpacket=$newpacket
    cp /var/log/syslog /syslogcopy
    echo .
    sleep 0.5
fi
done
